/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_SERVERSTUB_H_
#define JSONRPC_CPP_STUB_SERVERSTUB_H_

#include <jsonrpccpp/server.h>

class serverstub : public jsonrpc::AbstractServer<serverstub>
{
    public:
        serverstub(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<serverstub>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("addUser", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_OBJECT, NULL), &serverstub::addUserI);
            this->bindAndAddMethod(jsonrpc::Procedure("removeUser", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_INTEGER, NULL), &serverstub::removeUserI);
            this->bindAndAddMethod(jsonrpc::Procedure("getUser", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_ARRAY, "param1",jsonrpc::JSON_INTEGER, NULL), &serverstub::getUserI);
            this->bindAndAddMethod(jsonrpc::Procedure("getUserCount", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_INTEGER,  NULL), &serverstub::getUserCountI);
            this->bindAndAddMethod(jsonrpc::Procedure("removeLog", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_INTEGER,"param2",jsonrpc::JSON_INTEGER, NULL), &serverstub::removeLogI);
        }

        inline virtual void addUserI(const Json::Value &request, Json::Value &response)
        {
            response = this->addUser(request[0u]);
        }
        inline virtual void removeUserI(const Json::Value &request, Json::Value &response)
        {
            response = this->removeUser(request[0u].asInt());
        }
        inline virtual void getUserI(const Json::Value &request, Json::Value &response)
        {
            response = this->getUser(request[0u].asInt());
        }
        inline virtual void getUserCountI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getUserCount();
        }
        inline virtual void removeLogI(const Json::Value &request, Json::Value &response)
        {
            response = this->removeLog(request[0u].asInt(), request[1u].asInt());
        }
        virtual bool addUser(const Json::Value& param1) = 0;
        virtual bool removeUser(int param1) = 0;
        virtual Json::Value getUser(int param1) = 0;
        virtual int getUserCount() = 0;
        virtual bool removeLog(int param1, int param2) = 0;
};

#endif //JSONRPC_CPP_STUB_SERVERSTUB_H_
